version: '3'

services:
  movie-service:
    container_name: movie-service
    build: .
    ports:
      - ${SERVER_PORT}:8081
    restart: on-failure
    depends_on:
      - movie-service-db

  movie-service-db:
    image: postgres:latest
    container_name: movie-service-db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST=${DB_HOST}
    ports:
      - '${DB_PORT}:5432'